---
title: "Lab 03 - Degree Centrality - INSTRUCTIONS"
date: "CRJ 507 Social Network Analysis"
output: 
  html_document:
    df_print: paged
    theme: cosmo
    highlight: haddock
    toc: yes
    toc_float: yes
    code_fold: show
    self_contained: true
---

<style>
body {
text-align: justify}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set (echo = TRUE )
```

# Introduction

The purpose of this lab is to familiarize yourself with calculating degree centrality and degree centralization scores for undirected and directed networks in *R*. Please review the [Degree Centrality](https://jacobtnyoung.github.io/snaca-textbook/snaca-centrality-degree.html) chapter of the [Social Network Analysis for Crime Analysts](https://jacobtnyoung.github.io/snaca-textbook/index.html) textbook and the [Degree Centrality and Centralization](https://jacobtnyoung.github.io/snaca-r/snaca-r-degree-centrality.html) tutorial in the [Social Network Analysis for Crime Analysts using R](https://jacobtnyoung.github.io/snaca-r/index.html) textbook prior to beginning this lab.    

In Parts I and II of this lab we will use two new networks (described below). In Part III, you will use the two networks you created from [Lab 1](../labs/lab-01-instructions.html) and [Lab 2](../labs/lab-02-instructions.html).

<br>

## Part I: Working with an Undirected Network

For this part of the lab you will use data from [Thomas Grund and James Densley's study](https://journals.sagepub.com/doi/full/10.1177/1043986214553377) of ties among members of an inner-city gang in London, England. The network is undirected, binary ties collected from anonymized arrests data. We will refer to this network as the `LondonGangNet`. Note that the object is of class `network`. To coerce the object to be an object of class `matrix`, use the `as.matrix()` function.

<br>

For the `LondonGangNet` network, do the following:  

1. Plot the network using the `gplot()` function.    
2. Calculate the degree centrality score for each actor.  
3. Calculate the standardized degree centrality score for each actor.  
4. Calculate the mean degree centrality score.  
5. Calculate the graph centralization for degree centrality.  
6. Interpret the graph centralization score. What does it tell us about the distribution of degree centrality scores in the network?   

<br>

## Part II: Working with a Directed Network

For this part of the lab you will use data from [Mangia Natarajan's study](https://link.springer.com/article/10.1007/s10940-006-9007-x) of a large cocaine trafficking organization in New York City. The network is directed, binary ties of communication between individuals collected from police wiretaps of 151 telephone conversations. We will refer to this network as the `CocaineDealingNet`. Note that the object is of class `network`. To coerce the object to be an object of class `matrix`, use the `as.matrix()` function.

<br>

For the `CocaineDealingNet` network, do the following:  

1. Plot the network using the `gplot()` function.    
2. Calculate the indegree and outdegree centrality scores for each actor.  
3. Calculate the standardized indegree and outdegree centrality scores for each actor.  
4. Calculate the mean indegree and mean outdegree centrality scores.  
5. Interpret each mean centrality score and compare them. Is one larger than the other? What does this mean?
6. Calculate the graph centralization for indegree and outdegree centrality.  
7. Interpret each graph centralization score and comapre them. Is one larger than the other? What does this mean?  

<br>

## Part III:

Pick **one** of your networks you created in [Lab 1](../labs/lab-01-instructions.html) and [Lab 2](../labs/lab-02-instructions.html) and do the following:

  * If the network is *undirected*, repeat the steps in Part I.  
  
  * If the network is *directed*, repeat the steps in Part II.

<br>
<br>

# How to Submit

Download the [template for this lab](../labs/templates/lab-03-LastName.zip?raw=true) prior to beginning the lab. **The template contains code for accessing the data files**.

<br>

### Knitting to HTML

When you have completed your assignment, click the "Knit" button to render your `.RMD` file into a `.HTML` report.

<br>

### Special Instructions

Upload both your `.RMD` and `.HTML` files to the appropriate link for this assignment on the Canvas page for this course.

<br>

### Before You Submit

Remember to ensure the following before submitting your assignment.

1. Name your files using this format: **Lab-##-LastName.rmd** and **Lab-##-LastName.html**
2. Show both the solution for your code and write out your answers in the body text 

See [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) for examples of common conventions.

<br>
<br>

### Common Knitting Issues

`.RMD` files are knit into `.HTML` and other formats procedural, or line-by-line.

* An error in code when knitting will halt the process; error messages will tell you the specific line with the error
* Certain functions like `install.packages()` or `setwd()` are bound to cause errors in knitting 
* Altering a dataset or variable in one chunk will affect their use in all later chunks
* If an object is "not found", make sure it was created or loaded with `library()` in a previous chunk

**If All Else Fails:** If you cannot determine and fix the errors in a code chunk that's preventing you from knitting your document, add `eval = FALSE` inside the brackets of `{r}` at the beginning of a chunk to ensure that R does not attempt to evaluate it, that is: `{r eval = FALSE}`. This will prevent an erroneous chunk of code from halting the knitting process.  

<br>

____

<br>

##### ***Please*** report any needed corrections to the [Issues](https://github.com/Watts-College/crj-507-spring-2025/issues/new) page. Thanks!

<br>
<br>